# -*- coding: utf-8 -*-
"""Generate the core paper figures from the per-scope run outputs.

Reads the run directory produced by the orchestrator and writes vector PDFs into
<run>/figures/, each from the gallery scope that matches its research question:
  - rq1_paradigm.pdf       <- paradigm/ (matched 954): native vs prototype vs R@1
  - gallery_strategy.pdf   <- deployment/ (24): K-shot curves (Strategy A/B/C)
  - ood.pdf                <- deployment/ (24): OOD AUROC + FPR95 per method
  - retention.pdf          <- deployment/ (24): old/new after gallery expansion
  - rq5_ablation.pdf       <- deployment/ (24): backbone/loss across axes
  - ce_train_robustness.pdf<- full vs ce-train prototype/R@1 (RQ1 fairness control)

    python -m swid_retrieval.visualize [run_dir]

These are clean draft figures; restyle for journal camera-ready as needed.
"""

import json
import os
import shutil
import sys
from pathlib import Path

from . import config


def _run_dir(argv):
    if len(argv) > 1:
        return Path(argv[1])
    stamp = os.environ.get("FULL954_RUN_STAMP", "overnight")
    return Path(os.environ.get(
        "FULL954_RESULTS_DIR", config.ROOT_PATH / "results" / f"paper_reframe_full954_{stamp}"))


def _read_csv(p):
    import pandas as pd
    return pd.read_csv(p) if Path(p).exists() else None


def _read_json(p):
    return json.load(open(p)) if Path(p).exists() else None


def _save(fig, out):
    fig.tight_layout()
    fig.savefig(out, bbox_inches="tight")
    print(f"saved {out}")


def _copy_first_existing(candidates, dst):
    for p in candidates:
        p = Path(p)
        if p.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(p, dst)
            print(f"copied {p} -> {dst}")
            return True
    return False


def copy_static_figures(run_root, fig_dir):
    """Copy non-matplotlib paper assets into the run-local figures directory.

    These figures are static or generated by the review evidence interpretability
    pass, so they are not created by the core plotting functions.
    """
    repo_root = Path(__file__).resolve().parent.parent
    static_sources = {
        "sc_urd_architecture_py.png": [
            repo_root / "paper_figures" / "sc_urd_architecture_py.png",
            repo_root / "paper_reframe" / "figures" / "sc_urd_architecture_py.png",
            repo_root / "report_assets" / "sc_urd_architecture_py.png",
        ],
    }
    for idx in ("02", "03", "05"):
        name = f"scurd_occlusion_case_{idx}.png"
        static_sources[name] = [
            run_root / "deployment" / "review_evidence" / "figures" / name,
            repo_root / "paper_figures" / name,
            repo_root / "paper_reframe" / "review_evidence" / "figures" / name,
        ]
    for name, candidates in static_sources.items():
        if not _copy_first_existing(candidates, fig_dir / name):
            print(f"  static figure missing: {name}")


def fig_rq1_paradigm(para_dir, fig_dir):
    import matplotlib.pyplot as plt
    import numpy as np
    df = _read_csv(para_dir / "variance_evidence" / "headline_recomputed_selected_gallery.csv")
    if df is None:
        print("  skip rq1_paradigm (no headline csv)"); return
    df = df.sort_values("E1A_prototype_macro", ascending=False)
    methods = df["method"].tolist()
    proto = df["E1A_prototype_macro"].to_numpy(dtype=float)
    r1 = df["E1A_public_id_macro_R1"].to_numpy(dtype=float)
    native = float(df["E1A_native_ce_macro"].dropna().iloc[0]) if df["E1A_native_ce_macro"].notna().any() else None
    x = np.arange(len(methods)); w = 0.38
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(x - w / 2, proto, w, label="Prototype (anchor-matched)")
    ax.bar(x + w / 2, r1, w, label="R@1 (all gallery images)")
    if native is not None:
        ax.axhline(native, ls="--", color="k", lw=1.2, label=f"CE native (954-way) = {native:.3f}")
    ax.set_xticks(x); ax.set_xticklabels(methods, rotation=30, ha="right")
    ax.set_ylabel("Public-ID accuracy")
    ax.legend(fontsize=8)
    _save(fig, fig_dir / "rq1_paradigm.pdf"); plt.close(fig)


def fig_gallery_strategy(dep_dir, fig_dir):
    import matplotlib.pyplot as plt
    df = _read_csv(dep_dir / "variance_evidence" / "gallery_resampling_variance.csv")
    if df is None:
        print("  skip gallery_strategy (no csv)"); return
    fig, axes = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
    for ax, strat in zip(axes, ["B_public_only", "C_mixed"]):
        sub = df[df["strategy"] == strat]
        for m in sorted(sub["method"].unique()):
            s = sub[sub["method"] == m]
            s = s[s["K"].astype(str).isin(["1", "3", "5", "10"])]
            if s.empty:
                continue
            ks = s["K"].astype(int); ys = s["mean"].astype(float)
            ax.plot(ks, ys, marker="o", label=m, lw=1.6 if m == "SC-URD" else 1.0,
                    alpha=1.0 if m == "SC-URD" else 0.7)
        ax.text(0.02, 0.96, strat.replace("_", " "), transform=ax.transAxes,
                va="top", ha="left", fontsize=9)
        ax.set_xlabel("references / species (K)"); ax.set_xticks([1, 3, 5, 10])
    axes[0].set_ylabel("macro Top-1 (deployment gallery)")
    axes[1].legend(fontsize=7)
    _save(fig, fig_dir / "gallery_strategy.pdf"); plt.close(fig)


def _ood_dict(obj):
    out = {}
    block = (obj or {}).get("ood", obj or {})
    for m, v in block.items():
        if isinstance(v, dict):
            au = v.get("AUROC", {}).get("mean") if isinstance(v.get("AUROC"), dict) else v.get("AUROC")
            fp = v.get("FPR95", {}).get("mean") if isinstance(v.get("FPR95"), dict) else v.get("FPR95")
            if au is not None:
                out[m] = (float(au), float(fp) if fp is not None else None)
    return out


def fig_ood(dep_dir, fig_dir):
    import matplotlib.pyplot as plt
    import numpy as np
    d = _ood_dict(_read_json(dep_dir / "variance_evidence" / "rq2_ood_full_gallery.json"))
    if not d:
        print("  skip ood (no json)"); return
    methods = sorted(d, key=lambda m: d[m][0], reverse=True)
    au = [d[m][0] for m in methods]; fp = [d[m][1] for m in methods]
    x = np.arange(len(methods)); w = 0.38
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(x - w / 2, au, w, label="AUROC ↑")
    ax.bar(x + w / 2, fp, w, label="FPR95 ↓")
    ax.set_xticks(x); ax.set_xticklabels(methods, rotation=30, ha="right")
    ax.set_ylabel("score")
    ax.legend(fontsize=8)
    _save(fig, fig_dir / "ood.pdf"); plt.close(fig)


def fig_retention(dep_dir, fig_dir):
    import matplotlib.pyplot as plt
    import numpy as np
    obj = _read_json(dep_dir / "variance_evidence" / "rq3_adaptation_full_gallery_partial.json")
    g = (obj or {}).get("gallery_extension", {})
    rows = [(m, v.get("old_id_mean"), v.get("new_50_mean")) for m, v in g.items() if isinstance(v, dict)]
    if not rows:
        print("  skip retention (no json)"); return
    rows.sort(key=lambda r: (r[1] or 0), reverse=True)
    methods = [r[0] for r in rows]; old = [r[1] for r in rows]; new = [r[2] for r in rows]
    x = np.arange(len(methods)); w = 0.38
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(x - w / 2, old, w, label="old-species (after +50)")
    ax.bar(x + w / 2, new, w, label="new-species")
    ax.set_xticks(x); ax.set_xticklabels(methods, rotation=30, ha="right")
    ax.set_ylabel("accuracy")
    ax.legend(fontsize=8)
    _save(fig, fig_dir / "retention.pdf"); plt.close(fig)


def fig_rq5(dep_dir, fig_dir):
    import matplotlib.pyplot as plt
    import numpy as np
    df = _read_csv(dep_dir / "variance_evidence" / "rq5_backbone_loss_full_gallery.csv")
    if df is None:
        print("  skip rq5 (no csv)"); return
    methods = df["method"].tolist()
    axes_cols = [("exp1a_mean", "RQ1 R@1"), ("ood_auroc", "OOD AUROC"), ("exp3_old", "retention")]
    x = np.arange(len(methods)); w = 0.26
    fig, ax = plt.subplots(figsize=(8, 4))
    for i, (c, lbl) in enumerate(axes_cols):
        if c in df:
            ax.bar(x + (i - 1) * w, df[c].astype(float), w, label=lbl)
    ax.set_xticks(x); ax.set_xticklabels(methods, rotation=30, ha="right")
    ax.set_ylabel("score")
    ax.legend(fontsize=8)
    _save(fig, fig_dir / "rq5_ablation.pdf"); plt.close(fig)


def fig_robustness(run_root, fig_dir):
    import matplotlib.pyplot as plt
    import numpy as np
    full = _read_csv(run_root / "paradigm" / "variance_evidence" / "headline_recomputed_selected_gallery.csv")
    ce = _read_csv(run_root / "ce_train_robustness" / "variance_evidence" / "headline_recomputed_selected_gallery.csv")
    if full is None or ce is None:
        print("  skip robustness (missing paradigm/ce_train headline)"); return
    full = full.set_index("method"); ce = ce.set_index("method")
    methods = [m for m in full.index if m in ce.index]
    fp = [float(full.loc[m, "E1A_prototype_macro"]) for m in methods]
    cp = [float(ce.loc[m, "E1A_prototype_macro"]) for m in methods]
    x = np.arange(len(methods)); w = 0.38
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(x - w / 2, fp, w, label="Full 954 gallery")
    ax.bar(x + w / 2, cp, w, label="CE-train-only gallery")
    ax.set_xticks(x); ax.set_xticklabels(methods, rotation=30, ha="right")
    ax.set_ylabel("Prototype accuracy")
    ax.legend(fontsize=8)
    _save(fig, fig_dir / "ce_train_robustness.pdf"); plt.close(fig)


def fig_vn26(nat_dir, fig_dir):
    """fig5a: SWI_pool→VN26_all R@1 per method; fig5b: SC-URD cross-mag heatmap."""
    import matplotlib.pyplot as plt
    import numpy as np
    obj = _read_json(nat_dir / "rq4_generalization.json")
    if not obj:
        print("  skip vn26 (no rq4 json)"); return
    a = obj.get("cross_domain", {})
    pairs = [(m, a[m].get("SWI_pool", {}).get("VN26_all", {}).get("mean"))
             for m in a if a[m].get("SWI_pool", {}).get("VN26_all", {}).get("mean") is not None]
    if pairs:
        pairs.sort(key=lambda kv: kv[1], reverse=True)
        methods = [m for m, _ in pairs]; vals = [v for _, v in pairs]
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.bar(np.arange(len(methods)), vals)
        ax.set_xticks(np.arange(len(methods))); ax.set_xticklabels(methods, rotation=30, ha="right")
        ax.set_ylabel("SWI-pool → VN26-all R@1")
        _save(fig, fig_dir / "vn26_swi_to_vn26.pdf"); plt.close(fig)
    # fig5b: SC-URD cross-magnification heatmap.
    b = obj.get("cross_magnification", {}).get("SC-URD", {})
    if b:
        gkeys = sorted(b); qkeys = sorted({q for g in b for q in b[g]})
        mat = np.array([[b.get(g, {}).get(q, {}).get("mean", np.nan) for q in qkeys] for g in gkeys])
        fig, ax = plt.subplots(figsize=(5, 4))
        im = ax.imshow(mat, aspect="auto", cmap="viridis")
        ax.set_xticks(range(len(qkeys))); ax.set_xticklabels(qkeys, rotation=45, ha="right")
        ax.set_yticks(range(len(gkeys))); ax.set_yticklabels(gkeys)
        ax.set_xlabel("query mag"); ax.set_ylabel("gallery mag")
        fig.colorbar(im, ax=ax)
        _save(fig, fig_dir / "vn26_cross_mag.pdf"); plt.close(fig)


def fig_kshot(nat_dir, fig_dir):
    """fig3b: OOD-only K-shot open-set retrieval curves."""
    import matplotlib.pyplot as plt
    obj = _read_json(nat_dir / "rq2_kshot.json")
    ks = (obj or {}).get("kshot_retrieval", {})
    if not ks:
        print("  skip kshot (no json)"); return
    fig, ax = plt.subplots(figsize=(7, 4))
    for m, kd in ks.items():
        xs = [k for k in (1, 3, 5, 10) if str(k) in {str(x) for x in kd}]
        ys = [kd[str(k)]["mean"] if str(k) in kd else kd.get(k, {}).get("mean") for k in xs]
        xs2, ys2 = zip(*[(k, y) for k, y in zip(xs, ys) if y is not None]) if any(y is not None for y in ys) else ([], [])
        if xs2:
            ax.plot(xs2, ys2, marker="o", lw=1.6 if m == "SC-URD" else 1.0, alpha=1.0 if m == "SC-URD" else 0.7, label=m)
    ax.set_xlabel("OOD references / species (K)"); ax.set_ylabel("macro Top-1")
    ax.set_xticks([1, 3, 5, 10]); ax.legend(fontsize=7)
    _save(fig, fig_dir / "kshot.pdf"); plt.close(fig)


# ── SC-URD memory-mode ablation + discussion figures (paper fig6b / fig6 / fig_discussion_*) ──
# Ported from generate_all_figures_from_json.py (fig6b_scurd L453, fig6_compound L499,
# fig_discussion_rq3 L552, fig_discussion_rq5 L586, fig_discussion_ood L635), re-pointed
# at the package's own full-954 artifacts instead of the legacy paper_reframe/*.json.
_DISC_PALETTE = {
    "ImageNet": "#7f7f7f", "CLIP": "#17becf", "DINOv2": "#8B4789",
    "CE-Full": "#C44E52", "CE-Narrow": "#E8877F", "ArcFace-557": "#4C72B0",
    "ArcFace-954": "#6F8EB6", "ProtoNet": "#55A868", "SupCon": "#64B5CD",
    "Fusion": "#D6A517", "SC-URD": "#E87722",
}
_SCURD_MODES = ["raw", "centered", "logmeanexp", "prototype_mix",
                "centered_logmeanexp", "centered_prototype_mix"]


def _scurd_memory_rows(dep_dir):
    """[(mode, exp1a, ood_auroc, exp3_old), ...] from the SC-URD memory-mode CSV."""
    df = _read_csv(dep_dir / "variance_evidence" / "rq5_scurd_memory_modes_full_gallery.csv")
    if df is None:
        return None
    by_mode = {str(r["memory_mode"]): r for _, r in df.iterrows()}
    rows = []
    for mode in _SCURD_MODES:
        if mode in by_mode:
            r = by_mode[mode]
            rows.append((mode, float(r.get("exp1a_mean", 0) or 0),
                         float(r.get("ood_auroc", 0) or 0), float(r.get("exp3_old", 0) or 0)))
    return rows or None


def _plot_scurd_ablation(ax, rows, selected_mode):
    import numpy as np
    labels = [m.replace("_", "\n") for m, *_ in rows]
    e1 = [r[1] for r in rows]; ood = [r[2] for r in rows]; e3 = [r[3] for r in rows]
    x = np.arange(len(labels))
    ax.plot(x, e1, "o-", label="Public-ID R@1", color="#4C72B0", lw=1.8)
    ax.plot(x, ood, "s-", label="OOD AUROC", color="#2CA02C", lw=1.8)
    ax.plot(x, e3, "D-", label="Old-species retention", color="#D62728", lw=1.8)
    ax.set_xticks(x); ax.set_xticklabels(labels, fontsize=8)
    sel = (selected_mode or "centered").replace("_", "\n")
    if sel in labels:
        i = labels.index(sel)
        ax.axvspan(i - 0.32, i + 0.32, alpha=0.12, color="#E87722", zorder=0)
        ax.annotate("selected", xy=(i, min(1.0, max(e1[i], ood[i], e3[i]) + 0.055)),
                    xytext=(0, 6), textcoords="offset points", ha="center",
                    fontsize=8, color="#E87722")
    ax.set_ylim(0, 1.05); ax.grid(alpha=0.3); ax.legend(fontsize=8)


def fig_rq5_scurd_ablation(dep_dir, fig_dir):
    """fig6b: SC-URD memory-mode ablation (R@1 / OOD AUROC / retention across modes)."""
    import matplotlib.pyplot as plt
    rows = _scurd_memory_rows(dep_dir)
    if not rows:
        print("  skip rq5_scurd_ablation (no memory-mode csv)"); return
    fig, ax = plt.subplots(figsize=(7.0, 4.8))
    _plot_scurd_ablation(ax, rows, getattr(config, "SCURD_MODE", "centered"))
    _save(fig, fig_dir / "rq5_scurd_ablation.pdf"); plt.close(fig)


def fig_rq5_compound(dep_dir, fig_dir):
    """fig6: compound 6a (backbone/loss bars) + 6b (SC-URD memory modes)."""
    import matplotlib.pyplot as plt
    import numpy as np
    df = _read_csv(dep_dir / "variance_evidence" / "rq5_backbone_loss_full_gallery.csv")
    rows = _scurd_memory_rows(dep_dir)
    if df is None and not rows:
        print("  skip fig6 compound (no rq5 csv)"); return
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    if df is not None:
        methods = df["method"].tolist(); x = np.arange(len(methods)); w = 0.26
        for i, (c, lbl) in enumerate([("exp1a_mean", "RQ1 R@1"), ("ood_auroc", "OOD AUROC"),
                                      ("exp3_old", "retention")]):
            if c in df:
                axes[0].bar(x + (i - 1) * w, df[c].astype(float), w, label=lbl)
        axes[0].set_xticks(x); axes[0].set_xticklabels(methods, rotation=30, ha="right")
        axes[0].set_ylabel("score"); axes[0].legend(fontsize=8)
    if rows:
        _plot_scurd_ablation(axes[1], rows, getattr(config, "SCURD_MODE", "centered"))
    _save(fig, fig_dir / "fig6_rq5_scurd_ablation.pdf"); plt.close(fig)


def fig_discussion_rq5(dep_dir, fig_dir):
    """fig_discussion_rq5_tradeoff: SC-URD R@1 vs OOD AUROC across memory modes."""
    import matplotlib.pyplot as plt
    rows = _scurd_memory_rows(dep_dir)
    if not rows:
        print("  skip discussion_rq5 (no memory-mode csv)"); return
    fig, ax = plt.subplots(figsize=(8.2, 5.2))
    offsets = {"raw": (8, -24), "centered": (8, 18), "logmeanexp": (-58, 18),
               "prototype_mix": (8, -40), "centered_logmeanexp": (-74, -28),
               "centered_prototype_mix": (-108, -18)}
    for mode, e1, ood, _ in rows:
        ax.scatter(e1, ood, s=130, color="#E87722", alpha=0.85, edgecolor="white", linewidth=0.7)
        dx, dy = offsets.get(mode, (10, 8))
        ax.annotate(mode.replace("_", "\n"), (e1, ood), xytext=(dx, dy),
                    textcoords="offset points", fontsize=7,
                    arrowprops=dict(arrowstyle="-", lw=0.45, color="#777", alpha=0.65),
                    bbox=dict(boxstyle="round,pad=0.15", fc="white", ec="none", alpha=0.75))
    ax.set_xlabel("Public-ID cross-domain R@1"); ax.set_ylabel("OOD AUROC")
    ax.grid(alpha=0.3)
    _save(fig, fig_dir / "fig_discussion_rq5_tradeoff.pdf"); plt.close(fig)


def fig_discussion_rq3(dep_dir, fig_dir):
    """fig_discussion_rq3_stability_plasticity: old vs new accuracy after +50 OOD."""
    import matplotlib.pyplot as plt
    obj = _read_json(dep_dir / "variance_evidence" / "rq3_adaptation_full_gallery_partial.json")
    g = (obj or {}).get("gallery_extension", {})
    rows = [(m, v.get("old_id_mean"), v.get("new_50_mean")) for m, v in g.items()
            if isinstance(v, dict) and v.get("old_id_mean") is not None and v.get("new_50_mean") is not None]
    if not rows:
        print("  skip discussion_rq3 (no adaptation json)"); return
    rows.sort(key=lambda r: (r[1], r[2]))
    fig, ax = plt.subplots(figsize=(8.0, 5.8))
    label_offsets = [(12, 8), (12, -14), (12, 18), (12, -24), (12, 0), (12, 28),
                     (-58, 10), (-62, -12), (-70, 20), (-68, 0), (-68, 30), (-72, -22)]
    for idx, (m, old_after, new_after) in enumerate(rows):
        color = _DISC_PALETTE.get(m, "#777")
        marker = "D" if m == "SC-URD" else ("X" if m.startswith("CE") else "o")
        ax.scatter(old_after, new_after, s=90, color=color, marker=marker,
                   edgecolor="white", linewidth=0.8, zorder=3)
        dx, dy = label_offsets[idx % len(label_offsets)]
        ax.annotate(m, (old_after, new_after), xytext=(dx, dy), textcoords="offset points",
                    fontsize=7.5, arrowprops=dict(arrowstyle="-", lw=0.45, color="#777", alpha=0.65),
                    bbox=dict(boxstyle="round,pad=0.15", fc="white", ec="none", alpha=0.72))
    ax.set_xlabel("Old species accuracy after extension")
    ax.set_ylabel("New species accuracy after extension")
    ax.grid(alpha=0.3)
    _save(fig, fig_dir / "fig_discussion_rq3_stability_plasticity.pdf"); plt.close(fig)


def fig_discussion_ood(nat_dir, fig_dir):
    """fig_discussion_ood_score_distribution: per-method OOD−ID distance separation."""
    import matplotlib.pyplot as plt
    obj = _read_json(nat_dir / "rq2_ood_extended.json")
    sep = (obj or {}).get("ood_score_separation", {})
    sep = {m: v for m, v in sep.items() if v is not None}
    if not sep:
        print("  skip discussion_ood (no ood separation in rq2_ood_extended.json)"); return
    methods = sorted(sep, key=lambda m: sep[m], reverse=True)
    fig, ax = plt.subplots(figsize=(7, 4.2))
    ax.bar(methods, [sep[m] for m in methods],
           color=[_DISC_PALETTE.get(m.split("-")[0], "#777") for m in methods],
           alpha=0.85, edgecolor="white")
    ax.set_ylabel("Mean distance separation (OOD − ID)")
    ax.tick_params(axis="x", rotation=25); ax.grid(axis="y", alpha=0.3)
    _save(fig, fig_dir / "fig_discussion_ood_score_distribution.pdf"); plt.close(fig)


def main(argv=None):
    argv = argv if argv is not None else sys.argv
    try:
        import matplotlib
        matplotlib.use("Agg")
    except Exception as e:  # noqa: BLE001
        print(f"matplotlib unavailable ({e}); skipping figures."); return
    rd = _run_dir(argv)
    fig_dir = rd / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)
    para, dep, nat = rd / "paradigm", rd / "deployment", rd / "native_experiments"
    print(f"Figures -> {fig_dir}")
    for fn in (lambda: fig_rq1_paradigm(para, fig_dir),
               lambda: fig_gallery_strategy(dep, fig_dir),
               lambda: fig_ood(dep, fig_dir),
               lambda: fig_retention(dep, fig_dir),
               lambda: fig_rq5(dep, fig_dir),
               lambda: fig_rq5_scurd_ablation(dep, fig_dir),
               lambda: fig_rq5_compound(dep, fig_dir),
               lambda: fig_discussion_rq5(dep, fig_dir),
               lambda: fig_discussion_rq3(dep, fig_dir),
               lambda: fig_discussion_ood(nat, fig_dir),
               lambda: fig_robustness(rd, fig_dir),
               lambda: fig_vn26(nat, fig_dir),
               lambda: fig_kshot(nat, fig_dir)):
        try:
            fn()
        except Exception as e:  # noqa: BLE001
            print(f"  figure error: {e}")
    copy_static_figures(rd, fig_dir)
    _alias_to_paper_stems(fig_dir)


# Map our descriptive filenames to the exact \includegraphics stems in the .tex.
_PAPER_ALIASES = {
    "rq1_paradigm": "fig2a_rq1_paradigm",
    "gallery_strategy": "fig2b_rq1_gallery_strategy",
    "ood": "fig3a_rq2_ood_detection",
    "kshot": "fig3b_rq2_openset_retrieval",
    "vn26_swi_to_vn26": "fig5a_rq4_swi_to_vn26",
    "vn26_cross_mag": "fig5b_rq4_cross_magnification",
    "rq5_ablation": "fig6a_rq5_backbone_loss",
    "rq5_scurd_ablation": "fig6b_rq5_scurd_ablation",
}
# Figures already written under their exact paper stems (no alias copy needed):
#   fig6_rq5_scurd_ablation, fig_discussion_rq5_tradeoff,
#   fig_discussion_rq3_stability_plasticity, fig_discussion_ood_score_distribution.


def _alias_to_paper_stems(fig_dir):
    import shutil
    for src, dst in _PAPER_ALIASES.items():
        p = fig_dir / f"{src}.pdf"
        if p.exists():
            shutil.copy2(p, fig_dir / f"{dst}.pdf")
    print(f"  aliased figures to paper stems (fig2a/2b/3a/3b/5a/5b/6a/6b) in {fig_dir}")


if __name__ == "__main__":
    main(sys.argv)
